### ISSUE TITLE
Blank Screen with dependency on Grunt

### ISSUE THREAD

**Issue by dmarkscouk** [Blastitt/twitControl#3]
I installed your module, but am getting the following error:

```
pi@mirror1:~/MagicMirror $ npm install user-stream
magicmirror@2.0.0 /home/pi/MagicMirror
├── UNMET PEER DEPENDENCY grunt@1.0.1
└─┬ user-stream@0.0.7 
  └── oauth@0.9.8 

npm WARN grunt-yamllint@0.2.0 requires a peer of grunt@~0.4.0 but none was installed.
```

I've tried to install Grunt, but just get lots of errors.
If I run the module currently I just get a blank screen.

Any solution would be much appreciated.

Thanks, David

**Comment by TheBogueRat** [comment]
Just so the next person might benefit, I had this problem during the MM install and had to change the package.json entry for grunt to "~0.4.0" from "latest', then update again.
