### ISSUE TITLE
npm WARN twitControl@1.0.0 No repository field.

### ISSUE THREAD

**Issue by issagak** [Blastitt/twitControl#5]
Hello Blastitt

I was trying to use your module but gettign this waring below when I run the step 2 of the installation.
I went ahead and ignored this but the twiter feeds are not showing up on my mirror. I get the head but nothing else. Could the below be the issue?

I have 0 programming skills, I simply followed the directions you provided.

~/MagicMirror/modules/twitControl $ npm install
twitControl@1.0.0 /home/pi/MagicMirror/modules/twitControl
└─┬ user-stream@0.0.8 
  └── oauth@0.9.8 

npm WARN twitControl@1.0.0 No repository field.

**Comment by Blastitt** [comment]
The repository field is optional and for information purposes. It isn't the thing causing your problem, but I'll probably add it in the future anyway.

As for your problem, by head do you mean the "Twitter Feed" title thing? Are you receiving tweets, but they're not showing up on the mirror? Do you have the User Stream API keys configured correctly?

**Comment by issagak** [comment]
Yes i meant the hearder (title thing)

not sure what you mean configuring the User Stream API but I wen to Twitter and create an app there and go all the info i needed for the config.js file as shown below. Did I need to do anything else?

{
            		module: 'twitControl',
            		position: 'top_left',
            		config: {
                		maxNumTweets: 2,
                		api_keys: {
                    				consumer_key: ' I entered my consumer Key here',
                    				consumer_secret: 'I entered my consumer secret here',
                    				access_token_key: '58835777-I entered my Access Token key here',
                    				access_token_secret: 'and the secret here'
                				}
            			}
        	},

**Comment by issagak** [comment]
![twitter feed title](https://cloud.githubusercontent.com/assets/24981560/22433113/42c162e4-e6e5-11e6-98ac-7eeb14606269.png)

**Comment by Blastitt** [comment]
It seems like you set it up correctly. Check the mirror's error logs for anything unusual. Also note that it should only display tweets from your account and @mentions.

**Comment by issagak** [comment]
Oh OK got it - So it will only show the twits I send? can it show twits from this @SkySportsF1
I guess I will need to know the config option to show the twits from another account?
What is it if there is any. In your installation I only see 'maxNumTweets'

**Comment by Blastitt** [comment]
In node_helper.js change with: user to with: followings

**Comment by issagak** [comment]
I changed with user to with followings but still not seeing any twits. and I don't see any errors in my logs. Maybe the issue is with my twitter api keys. I'll take a look at that.

**Comment by issagak** [comment]
OK it seems to be working now. I'm not able to show my twits. The problem was that it only shows twits that were sent after I launch the MagicMirror. I changed the node_helper.js and added 'followings' instead of user. Will see.
Thank you so much Blastitt.
