### ISSUE TITLE
new Tweets on top / smaller font?

### ISSUE THREAD

**Issue by vimsi** [Blastitt/twitControl#9]
Hey Blastitt,
is there any chance to make the font of the tweets smaller (for lower res displays) so that you can read the complete tweet.
And could you please let the newest tweet be on top and teh older ones below?new->old order
I wish i could do it by my own but i have no idea how to... :(

**Comment by Blastitt** [comment]
Hi vimsi,

I've stopped supporting this project for the time being (I might come back to it later when I have more time). The font size should be an easy fix if you want to do it yourself, though. On line 58 of `twitControl.js`, add the word _small_ to the list of space separated CSS classes. This should make the tweet text the same size as the author. I think there's also _medium_ and _large_, so you can play around with sizes.

The tweet ordering is an even easier thing to modify. On line 55 of `twitControl.js`, just change `this.tweets` to `this.tweets.reverse()`.

When I get a chance, I'll officially add these features as options that you can toggle on/off in the config of the module so you don't have to edit the code yourself.

**Comment by vimsi** [comment]
Thank You so much for this!!!!
You Are Great!
